const API=window.EASY_BUBBLE_API_URL;let session,state={staff:[],branches:[],shifts:[],settings:{},payroll:[]};
try{session=JSON.parse(localStorage.getItem('eb_session'))}catch{}if(!session||session.role!=='admin'||session.expires<Date.now())location.href='index.html';
const qs=(s,p=document)=>p.querySelector(s),qsa=(s,p=document)=>[...p.querySelectorAll(s)],toast=t=>{const e=qs('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)};
function time24(v){let s=String(v||'').trim().replace('.',':');if(/^\d{3,4}$/.test(s)){s=s.padStart(4,'0');s=s.slice(0,2)+':'+s.slice(2)}const p=s.split(':');if(p.length===2&&Number(p[0])>=0&&Number(p[0])<24&&Number(p[1])>=0&&Number(p[1])<60)return p[0].padStart(2,'0')+':'+p[1].padStart(2,'0');return s}
function localYMD(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
qsa('.time24').forEach(x=>x.addEventListener('blur',()=>x.value=time24(x.value)));
async function call(action,body={}){const r=await fetch(API,{method:'POST',body:JSON.stringify({action,token:session.token,...body})});const j=await r.json();if(!j.success)throw Error(j.message||'ทำรายการไม่สำเร็จ');return j.data}
qsa('.tab').forEach(b=>b.onclick=()=>{qsa('.tab').forEach(x=>x.classList.remove('active'));qsa('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');qs('#'+b.dataset.panel).classList.add('active');if(b.dataset.panel==='payroll')loadPayroll()});
const formObj=f=>{const o=Object.fromEntries(new FormData(f).entries());qsa('.time24',f).forEach(x=>o[x.name]=time24(x.value));return o};
function setForm(f,obj){f.reset();Object.entries(obj||{}).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v??''})}
async function init(){try{state=await call('adminData');state.shifts=(state.shifts||[]).map(x=>({...x,start_time:time24(x.start_time),end_time:time24(x.end_time)}));fill();render();}catch(e){toast(e.message)}}
function fill(){qsa('.staff-select').forEach(s=>s.innerHTML='<option value="">เลือกพนักงาน</option>'+state.staff.filter(x=>x.status==='active').map(x=>`<option value="${x.staff_id}">${x.nickname||x.name}</option>`).join(''));const shiftOptions=state.shifts.filter(x=>x.status==='active').map(x=>`<option value="${x.shift_id}">${x.name} · ${x.start_time}–${x.end_time}</option>`).join('');qsa('.shift-select').forEach(s=>s.innerHTML='<option value="">เลือกกะงาน</option>'+shiftOptions);staffShift.innerHTML=shiftOptions;staffBranch.innerHTML=state.branches.map(x=>`<option value="${x.branch_id}">${x.name}</option>`).join('');setForm(qs('#settings form'),state.settings);payMonth.value=localYMD(new Date()).slice(0,7)}
function render(){const o=state.overview||{};summary.innerHTML=`<div class="card"><div class="muted">พนักงานทั้งหมด</div><div class="big-number">${o.active_staff||0}</div></div><div class="card"><div class="muted">มาทำงานวันนี้</div><div class="big-number">${o.present_today||0}</div></div><div class="card"><div class="muted">OT รอตรวจ</div><div class="big-number">${o.pending_ot||0}</div></div>`;attendance.innerHTML=(o.today||[]).length?`<div class="table-wrap"><table><thead><tr><th>พนักงาน</th><th>กะ</th><th>เข้า</th><th>ออก</th></tr></thead><tbody>${o.today.map(x=>`<tr><td>${x.staff_name}</td><td>${x.shift_name||'—'}</td><td>${x.clock_in||'—'}</td><td>${x.clock_out||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">ยังไม่มีใครบันทึกเวลา</div>';pending.innerHTML=(o.ot_items||[]).length?o.ot_items.map(x=>`<div class="notice" style="margin-bottom:10px"><b>${x.staff_name}</b> ขอ OT ${x.ot_hours} ชม.<div class="actions" style="margin-top:8px"><button class="btn btn-success" onclick="approveOT('${x.record_id}','approved')">อนุมัติ</button><button class="btn btn-danger" onclick="approveOT('${x.record_id}','rejected')">ปฏิเสธ</button></div></div>`).join(''):'<div class="empty">ไม่มีรายการค้างตรวจ</div>';staffTable.innerHTML=`<div class="table-wrap"><table><thead><tr><th>พนักงาน</th><th>สาขา</th><th>กะประจำ</th><th>ค่าแรง</th><th>สถานะ</th><th></th></tr></thead><tbody>${state.staff.map(x=>`<tr><td><b>${x.nickname||x.name}</b><br><span class="muted">${x.role==='admin'?'ผู้ดูแล':'พนักงาน'}</span></td><td>${x.branch_name||'—'}</td><td>${x.shift_name||'—'}</td><td>฿${Number(x.daily_rate||0).toLocaleString()}/วัน</td><td><span class="status ${x.status==='active'?'status-ok':'status-muted'}">${x.status==='active'?'ใช้งาน':'ปิดใช้งาน'}</span></td><td><button class="btn" onclick="openStaff('${x.staff_id}')">แก้ไข</button></td></tr>`).join('')}</tbody></table></div>`;shiftList.innerHTML=state.shifts.length?state.shifts.map(x=>`<div class="notice" style="margin-top:12px"><b>${x.name}</b><br><span class="muted">${x.start_time}–${x.end_time} · สายได้ ${x.late_grace_min||0} นาที · OT หลัง ${x.ot_grace_min||0} นาที · ${x.status==='active'?'ใช้งาน':'ปิดใช้งาน'}</span><button class="btn" style="float:right" onclick="openShift('${x.shift_id}')">แก้ไข</button></div>`).join(''):'<div class="empty">ยังไม่มีกะงาน</div>';branchList.innerHTML=state.branches.map(x=>`<div class="notice" style="margin-top:12px"><b>${x.name}</b><br><span class="muted">ระยะ ${x.allowed_radius_m} เมตร · ${x.lat&&x.lng?'มีพิกัดแล้ว':'ยังไม่มีพิกัด'}</span><button class="btn" style="float:right" onclick="openBranch('${x.branch_id}')">แก้ไข</button></div>`).join('')}
async function approveOT(id,status){try{await call('approveOT',{record_id:id,status});toast('บันทึกเรียบร้อย');await init()}catch(e){toast(e.message)}}
async function saveLeave(e){e.preventDefault();try{await call('saveLeave',formObj(e.target));toast('บันทึกวันลาแล้ว');e.target.reset()}catch(x){toast(x.message)}}
async function saveAdvance(e){e.preventDefault();try{await call('saveAdvance',formObj(e.target));toast('บันทึกเงินเบิกแล้ว');e.target.reset()}catch(x){toast(x.message)}}
function buildDays(){dayChoices.innerHTML='';const f=backfillForm.elements.date_from.value,t=backfillForm.elements.date_to.value;if(!f||!t)return;let d=new Date(f+'T00:00:00'),end=new Date(t+'T00:00:00'),n=0;while(d<=end&&n++<62){const v=localYMD(d),day=d.toLocaleDateString('th-TH',{weekday:'short',day:'numeric',month:'short'});dayChoices.insertAdjacentHTML('beforeend',`<label class="status status-muted"><input type="checkbox" value="${v}"> เว้น ${day}</label>`);d.setDate(d.getDate()+1)}}
backfillForm.elements.date_from.onchange=buildDays;backfillForm.elements.date_to.onchange=buildDays;
function applyBackfillShift(id){const x=state.shifts.find(s=>s.shift_id===id);if(!x)return;backfillForm.elements.shift_id.value=x.shift_id;backfillForm.elements.clock_in.value=time24(x.start_time);backfillForm.elements.clock_out.value=time24(x.end_time)}
backfillForm.elements.staff_id.onchange=()=>{const x=state.staff.find(s=>s.staff_id===backfillForm.elements.staff_id.value);if(x)applyBackfillShift(x.shift_id)};
backfillForm.elements.shift_id.onchange=()=>applyBackfillShift(backfillForm.elements.shift_id.value);
async function saveBackfill(e){e.preventDefault();const b=formObj(e.target);b.skip_dates=qsa('#dayChoices input:checked').map(x=>x.value);if(!confirm(`ยืนยันเพิ่มเวลาย้อนหลังช่วง ${b.date_from} ถึง ${b.date_to}?`))return;try{const d=await call('bulkUpsertTimesheets',b);toast(`เพิ่มสำเร็จ ${d.created} วัน ข้าม ${d.skipped} วัน`)}catch(x){toast(x.message)}}
async function loadPayroll(){if(!payMonth.value)return;payrollData.innerHTML='<div class="loader"></div>';try{state.payroll=await call('payrollPreview',{month:payMonth.value});payrollData.innerHTML=`<div class="table-wrap"><table><thead><tr><th>พนักงาน</th><th>วันทำงาน</th><th>ค่าแรง</th><th>OT</th><th>สาย</th><th>เบิก</th><th>ยอดสุทธิ</th></tr></thead><tbody>${state.payroll.map(x=>`<tr><td>${x.staff_name}</td><td>${x.days_worked}</td><td>฿${x.base_pay.toLocaleString()}</td><td>฿${x.ot_pay.toLocaleString()}</td><td>-฿${x.late_deduct.toLocaleString()}</td><td>-฿${x.advance_deduct.toLocaleString()}</td><td><b>฿${x.total_pay.toLocaleString()}</b></td></tr>`).join('')}</tbody></table></div>`;finalizeBtn.classList.toggle('hidden',!state.payroll.length)}catch(e){payrollData.innerHTML='<div class="empty">'+e.message+'</div>'}}
async function finalizePayroll(){if(!confirm('ยืนยันยอดเงินเดือนและบันทึกว่าจ่ายแล้วใช่ไหม?'))return;try{await call('finalizePayroll',{month:payMonth.value,items:state.payroll});toast('บันทึกเงินเดือนเรียบร้อย')}catch(e){toast(e.message)}}
function openStaff(id=''){const x=state.staff.find(s=>s.staff_id===id)||{role:'staff',status:'active',daily_rate:400,ot_rate:50,shift_id:(state.shifts.find(x=>x.status==='active')||{}).shift_id};setForm(staffModal.querySelector('form'),x);staffModalTitle.textContent=id?'แก้ไขพนักงาน':'เพิ่มพนักงาน';staffModal.classList.add('show')}
async function saveStaff(e){e.preventDefault();try{await call('saveStaff',formObj(e.target));staffModal.classList.remove('show');toast('บันทึกพนักงานแล้ว');await init()}catch(x){toast(x.message)}}
function openShift(id=''){const x=state.shifts.find(s=>s.shift_id===id)||{start_time:'09:00',end_time:'18:00',late_grace_min:15,ot_grace_min:15,status:'active'};setForm(shiftModal.querySelector('form'),x);shiftModalTitle.textContent=id?'แก้ไขกะงาน':'เพิ่มกะงาน';shiftModal.classList.add('show')}
async function saveShift(e){e.preventDefault();try{await call('saveShift',formObj(e.target));shiftModal.classList.remove('show');toast('บันทึกกะงานแล้ว');await init()}catch(x){toast(x.message)}}
function openBranch(id=''){const x=state.branches.find(s=>s.branch_id===id)||{allowed_radius_m:200};setForm(branchModal.querySelector('form'),x);branchModal.classList.add('show')}
function captureBranchGPS(){navigator.geolocation.getCurrentPosition(p=>{const f=branchModal.querySelector('form');f.elements.lat.value=p.coords.latitude;f.elements.lng.value=p.coords.longitude;toast('นำตำแหน่งปัจจุบันมาใส่แล้ว')},()=>toast('อ่านตำแหน่งไม่ได้ กรุณาเปิด GPS'),{enableHighAccuracy:true})}
async function saveBranch(e){e.preventDefault();try{await call('saveBranch',formObj(e.target));branchModal.classList.remove('show');toast('บันทึกสาขาแล้ว');await init()}catch(x){toast(x.message)}}
async function saveSettings(e){e.preventDefault();try{await call('saveSettings',{settings:formObj(e.target)});toast('บันทึกกฎแล้ว');await init()}catch(x){toast(x.message)}}
async function saveTelegram(e){e.preventDefault();try{await call('saveTelegram',formObj(e.target));toast('บันทึก Telegram แล้ว');e.target.elements.token.value=''}catch(x){toast(x.message)}}
function logout(){localStorage.removeItem('eb_session');location.href='index.html'}init();
